### PR TITLE
Fixes #43 to make codeclimate issue better

### LINKED ISSUE #43: Fix CodeClimate Issues
This is an entry level issue for users to become familiar with the Privly Project's code base. You should pick a file from [CodeClimate](https://codeclimate.com/github/privly/privly-firefox) and improve files per the recommendation of the programmatic code quality system.

Do not close this issue in your commits since this is intended to be a more permanent issue.

### PR DESCRIPTION
**Pull request by sudheesh001**

### CODE REVIEW

**Comment by smcgregor** [comment]
You should not put "Fixes #43" in the commit message since it will close the referenced issue. You are not fixing all the CodeClimate issues, you are improving the code for #43.

Can you open this PR on [privly-chrome](https://github.com/privly/privly-chrome) as well? I typically port changes from privly-chrome to privly-firefox.

**Comment by sudheesh001** [comment]
@smcgregor Sure, I didn't know that we needn't put the `Fixes #43`, that was generally the way I was working on Github :smile: Yeah sure, I'll open the PR on `privly-chrome` and rebase this PR with a different commit message if needed.

**Comment by smcgregor** [comment]
If you don't comment about the changes you made to the PR, it won't make its way back into the review queue.

**Comment by smcgregor** [comment]
Too long without update. Feel free to fix and reopen.

**Pull request closed without merging**
